<template>
<div id="add_token_modal" class="modal  fade" ref="modal">
    <div class="modal-dialog"><div class="modal-content">

    <div class="modal-header"> 
        <a class="close" @click.prevent="hideModal" >×</a>
        <h3 class="">Add Tokens</h3>
    </div>
    <div class="modal-body">
        <div class="control-group form-group row">
            <span class="control-label col-md-3">Conversion Pixel<span class=""></span></span>
            <textarea id="add_conversion_pixel_textarea"  @click="showPrompt(addConversionPixel || conversion_pixel)" :value="addConversionPixel || conversion_pixel" class="col-md-8" readonly="" style="min-height: 75pt;background-color: #fff;"></textarea>
        </div>
        <table class="table table-hover tablesorter">
        <thead>
            <tr>
                <th>Token Name</th>
                <th class="left">Description</th>
                <th></th>
            </tr>
        </thead>
        <tbody id="add_token_list">
            <tr>
                <td>client_ip</td>
                <td>The mobile IP address when conversion happened.</td>
                <td><input value ="client_ip" type="checkbox" /></td>
            </tr>
            <tr>
                <td>carrier</td>
                <td>The carrier name of the mobile when conversion happened.</td>
                <td><input value="carrier" type="checkbox" /></td>
            </tr>
            <tr>
                <td>android_id</td>
                <td>For Android devices only.</td>
                <td><input value="android_id" type="checkbox" /></td>
            </tr>
            <tr>
                <td>device_id</td>
                <td>General device id to support multiple device type.</td>
                <td><input value="device_id" type="checkbox" /></td>
            </tr>
            <tr>
                <td>idfa</td>
                <td>Apple's advertiser identifier with iOS 6+</td>
                <td><input value="idfa" type="checkbox" /></td>
            </tr>
            <tr>
                <td>google_adv_id</td>
                <td>Google's advertising identifier.</td>
                <td><input value="google_adv_id" type="checkbox" /></td>
            </tr>
            <tr>
                <td>mac</td>
                <td>MAC address of the phone's wifi adapter.</td>
                <td><input value="mac" type="checkbox" /></td>
            </tr>
            <tr>
                <td>imei</td>
                <td>IMEI number of the mobile device.</td>
                <td><input value="imei" type="checkbox" /></td>
            </tr>
            <tr>
                <td>active_time</td>
                <td>Active time of the conversion, such as install time.</td>
                <td><input value="active_time" type="checkbox" /></td>
            </tr>
            <tr>
                <td>oid</td>
                <td>The unique ID generated by advertiser for each conversion.</td>
                <td><input value="oid" type="checkbox" /></td>
            </tr>
            <tr>
                <td>adv_sub</td>
                <td>Advertiser sub specified in the conversion pixel.</td>
                <td><input value="adv_sub" type="checkbox" /></td>
            </tr>
            <tr>
                <td>adv_sub2</td>
                <td>Advertiser sub 2 specified in the conversion pixel.</td>
                <td><input value="adv_sub2" type="checkbox" /></td>
            </tr>
            <tr>
                <td>adv_sub3</td>
                <td>Advertiser sub 3 specified in the conversion pixel.</td>
                <td><input value="adv_sub3" type="checkbox" /></td>
            </tr>
            <tr>
                <td>adv_sub4</td>
                <td>Advertiser sub 4 specified in the conversion pixel.</td>
                <td><input value="adv_sub4" type="checkbox" /></td>
            </tr>
            <tr>
                <td>adv_sub5</td>
                <td>Advertiser sub 5 specified in the conversion pixel.</td>
                <td><input value="adv_sub5" type="checkbox" /></td>
            </tr>
            <tr>
                <td>adv_sub6</td>
                <td>Advertiser sub 6 specified in the conversion pixel.</td>
                <td><input value="adv_sub6" type="checkbox" /></td>
            </tr>
            <tr>
                <td>adv_sub7</td>
                <td>Advertiser sub 7 specified in the conversion pixel.</td>
                <td><input value="adv_sub7" type="checkbox" /></td>
            </tr>
            <tr>
                <td>adv_sub8</td>
                <td>Advertiser sub 8 specified in the conversion pixel.</td>
                <td><input value="adv_sub8" type="checkbox" /></td>
            </tr>
        </tbody>
    </table>
    </div>
    <div class="modal-footer"> <a href="javascript:;" class="btn secondary" data-dismiss="modal" @click.prevent="hideModal">Close</a></div>
    </div></div>
</div>
</template>
<script>
export default{
    props: ['modalState','hideModal','conversion_pixel','showPrompt'],
    data() {
        return {
            alertPop:"hide",
            alertMsg:"",
            addConversionPixel:""

        }
    },
    components: {
    },
    computed: {

    },
    methods: {
        toggleModal:function(msg) {
            $(this.$refs.modal).modal(msg)
        }
    },
    watch: {
        modalState: function (val) {
          this.toggleModal(val)
        }
    },
    mounted () {
        let that = this;
        $(this.$refs.modal).on('hidden.bs.modal', function () {
            that.hideModal()
        })

        $(this.$refs.modal).on('change','[type="checkbox"]', function () {
            that.addConversionPixel = that.conversion_pixel
            let $checkbox = $('[type="checkbox"]:checked', that.$refs.modal)
            $checkbox.each(function(){

                that.addConversionPixel += "&" + $(this).val() + "={" + $(this).val()+"}"
            })
            console.log(that.addConversionPixel)
        })


    }
}
</script>